isopp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

admin.sites.AdminSite.site_header = _("Administration")
admin.sites.AdminSite.site_title = _("Administration")
admin.sites.AdminSite.index_title = "ISOPP"


if settings.MAINTENANCE_MODE:
    urlpatterns = [
        re_path("/*", TemplateView.as_view(template_name="maintenance.html")),
    ]
else:
    urlpatterns = [
        path("", include("core.urls")),
        path("admin/", admin.site.urls),
        path("accounts/", include(("accounts.urls", "accounts"), namespace="accounts")),
        path("areas/", include(("areas.urls", "areas"), namespace="areas")),
        path("lang/", include("django.conf.urls.i18n")),
    ]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
        path("404/", TemplateView.as_view(template_name="404.html")),
        path("403/", TemplateView.as_view(template_name="403.html")),
        path("500/", TemplateView.as_view(template_name="500.html")),
    ] + urlpatterns

isopp/areas/models.py
import settings
from django.contrib.gis.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from utils.models import TimeStampedModel
from utils.queries import active_periods_filter, recent_periods_filter


class District(models.Model):
    name = models.CharField(_("name"), max_length=255, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("district")
        verbose_name_plural = _("districts")


class AreaQS(models.QuerySet):
    def valid(self):
        return self.filter(author__is_active=True, is_deleted=False)


class Area(TimeStampedModel):
    boundary = models.MultiPolygonField(_("boundary"))

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("author"),
        related_name="areas",
        on_delete=models.PROTECT,
    )

    district = models.ForeignKey(
        District,
        verbose_name=_("district"),
        related_name="areas",
        on_delete=models.PROTECT,
    )

    description = models.TextField(
        _("description"),
        help_text=_("Optional item"),
        blank=True,
    )

    is_deleted = models.BooleanField(_("is deleted?"), default=False, db_index=True)

    objects = models.Manager.from_queryset(AreaQS)()

    def get_absolute_url(self):
        return reverse("areas:detail", args=[self.id])

    def __str__(self):
        return _("Area") + f" #{self.id}"

    class Meta:
        verbose_name = _("area")
        verbose_name_plural = _("areas")


class SprayingPeriodQS(models.QuerySet):
    def recent(self, now):
        return self.filter(**recent_periods_filter(now))

    def active(self, now):
        return self.filter(**active_periods_filter(now))

    def inactive(self, now):
        return self.exclude(**active_periods_filter(now))


class SprayingPeriod(TimeStampedModel):
    class PestKind(models.IntegerChoices):
        FUNGI = 100, _("fungi")
        ANIMALS = 200, _("animals")
        PLANTS = 300, _("plants")

    pest_kind = models.SmallIntegerField(
        _("pest kind"),
        help_text=_("The type of pests against which the spray is applied"),
        choices=PestKind.choices,
    )
    executor = models.CharField(_("executor"), max_length=255)
    since = models.DateTimeField(_("since"))
    until = models.DateTimeField(_("until"))
    area = models.ForeignKey(
        "Area", verbose_name=_("area"), related_name="periods", on_delete=models.PROTECT
    )

    objects = models.Manager.from_queryset(SprayingPeriodQS)()

    def __str__(self):
        return _("Period") + f" #{self.id}"

    class Meta:
        verbose_name = _("spraying period")
        verbose_name_plural = _("spraying periods")

isopp/templates/inc/filter.html
{% load i18n %}
<div id="filter">
    <a class="filter filter-current"
       href="?filter=current"
       title="{% trans 'Current spraying periods' %}"
    >
        <i class="fa fa-filter"></i>
    </a>
    <a class="filter filter-future"
       href="?filter=future"
       title="{% trans 'Future spraying periods' %}"
    >
        <i class="fa fa-filter"></i>
    </a>
    <a class="filter filter-past"
       href="?filter=past"
       title="{% trans 'Past spraying periods' %}"
    >
        <i class="fa fa-filter"></i>
    </a>
    <a class="filter filter-inactive"
       href="?filter=inactive"
       title="{% trans 'Inactive spraying periods' %}"
    >
        <i class="fa fa-filter"></i>
    </a>
</div>
<script>
    const urlParams = new URLSearchParams(window.location.search);
    const filter = urlParams.get('filter');
    if (filter) {
        for (el of document.getElementsByClassName("filter-" + filter)) {
            el.classList.add("filter-active");
        }
    }
</script>

isopp/templates/inc/footer.html
{% load i18n %}
<div id="footer">
    <div class="footer-legend">
        <div class="footer-legend-past">{% trans 'Spraying took place within 1 week' %}</div>
        <div class="footer-legend-future">{% trans 'Spraying will take place within 24 hours' %}</div>
        <div class="footer-legend-current">{% trans 'Spraying in progress' %}</div>
    </div>
    <div class="footer-copy">
        <div>
            <span>&copy; 2019 – {% now 'Y' %} <a href="https://www.zonybezpesticidov.sk/">Zóny bez pesticídov</a></span>
        </div>
        <div>
            <span>Software: <a href="mailto:jsmesami@gmail.com">Ondřej Nejedlý</a></span>
        </div>
        <div>
            <span>Design: Artfeel</span>
        </div>
    </div>
</div>

isopp/templates/inc/languages.html
{% load i18n %}
{% load static %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}

{% for language in languages %}
    <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
        <input type="hidden" name="next" value="{{ redirect_to }}">
        <input type="hidden" name="language" value="{{ language.code }}">
        <button type="submit"
                title="{% trans language.name %}"
                class="btn"
                {% if language.code == LANGUAGE_CODE %}
                    disabled="disabled"
                {% endif %}>
            <img src="{% static 'flags/' %}{{ language.code }}.svg" alt="{{ language.code }}">
        </button>
    </form>
{% endfor %}

isopp/templates/inc/marker.html
<svg xmlns="http://www.w3.org/2000/svg">
    <symbol id="marker" viewBox="0 0 85.312 100">
        <path fill="#FFF"
              d="M42.656 100c-7.687 0-14.889-1.907-21.408-5.669-6.495-3.748-11.709-8.869-15.497-15.223C1.935 72.705 0 65.602
              0 57.995s1.935-14.709 5.751-21.113c3.789-6.354 9.002-11.476 15.498-15.223a42.254 42.254 0
              018.179-3.634V0h26.458v18.048a42.491 42.491 0 018.097 3.611c6.493 3.745 11.72 8.878 15.533 15.256 3.846 6.431
              5.797 13.523 5.797 21.08 0 7.556-1.95 14.647-5.797 21.08-3.813 6.377-9.04 11.51-15.533 15.256C57.463 98.093
              50.287 100 42.656 100z"></path>
        <g fill="currentColor">
            <circle cx="42.682" cy="58.01" r="6.945"></circle>
            <path d="M74.485 39.923c-3.311-5.536-7.788-9.932-13.432-13.188-3.49-2.013-7.167-3.402-11.029-4.17V5.861H35.289v16.693a35.98
            35.98 0 00-11.111 4.182c-5.644 3.256-10.107 7.638-13.391 13.147-3.283 5.508-4.925 11.545-4.925 18.112s1.642 12.604 4.925
            18.112c3.284 5.509 7.748 9.891 13.391 13.146 5.644 3.257 11.804 4.885 18.479 4.885 6.621 0 12.753-1.628 18.397-4.885
            5.644-3.256 10.121-7.652 13.432-13.187 3.311-5.536 4.966-11.561 4.966-18.072s-1.656-12.536-4.967-18.071zM61.664
            69.147c-1.981 3.419-4.653 6.119-8.018 8.1-3.365 1.98-7.028 2.972-10.99 2.972-4.016
            0-7.707-.991-11.071-2.972-3.365-1.98-6.038-4.681-8.019-8.1-1.981-3.419-2.971-7.137-2.971-11.152s.99-7.733
            2.971-11.153c1.98-3.419 4.653-6.119 8.019-8.1a21.465 21.465 0 013.703-1.727v8.903h14.736v-8.875a21.607 21.607
            0 013.622 1.699c3.364 1.981 6.036 4.681 8.018 8.1 1.98 3.419 2.972 7.137 2.972 11.153s-.991 7.734-2.972 11.152z"></path>
        </g>
    </symbol>
</svg>

isopp/templates/inc/periods_table.html
{% load i18n %}
<table class="table table-period table-sm table-borderless">
    {% for period in periods %}
        <tr class="pest"><th>{% trans 'pest kind' %}:</th><td>{{ period.get_pest_kind_display }}</td></tr>
        <tr class="executor"><th>{% trans 'executor' %}:</th><td>{{ period.executor }}</td></tr>
        <tr class="since"><th>{% trans 'from' %}:</th><td>{{ period.since|date:"SHORT_DATETIME_FORMAT" }}</td></tr>
        <tr class="until"><th>{% trans 'to' %}:</th><td>{{ period.until|date:"SHORT_DATETIME_FORMAT" }}</td></tr>
    {% endfor %}
</table>