isopp/areas/urls.py
from django.urls import path

from .views import CreateView, DetailView, UpdateView

urlpatterns = [
    path("detail/<pk>/", DetailView.as_view(), name="detail"),
    path("update/<pk>/", UpdateView.as_view(), name="update"),
    path("create/", CreateView.as_view(), name="create"),
]

isopp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

admin.sites.AdminSite.site_header = _("Administration")
admin.sites.AdminSite.site_title = _("Administration")
admin.sites.AdminSite.index_title = "ISOPP"


if settings.MAINTENANCE_MODE:
    urlpatterns = [
        re_path("/*", TemplateView.as_view(template_name="maintenance.html")),
    ]
else:
    urlpatterns = [
        path("", include("core.urls")),
        path("admin/", admin.site.urls),
        path("accounts/", include(("accounts.urls", "accounts"), namespace="accounts")),
        path("areas/", include(("areas.urls", "areas"), namespace="areas")),
        path("lang/", include("django.conf.urls.i18n")),
    ]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
        path("404/", TemplateView.as_view(template_name="404.html")),
        path("403/", TemplateView.as_view(template_name="403.html")),
        path("500/", TemplateView.as_view(template_name="500.html")),
    ] + urlpatterns

isopp/areas/models.py
import settings
from django.contrib.gis.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from utils.models import TimeStampedModel
from utils.queries import active_periods_filter, recent_periods_filter


class District(models.Model):
    name = models.CharField(_("name"), max_length=255, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("district")
        verbose_name_plural = _("districts")


class AreaQS(models.QuerySet):
    def valid(self):
        return self.filter(author__is_active=True, is_deleted=False)


class Area(TimeStampedModel):
    boundary = models.MultiPolygonField(_("boundary"))

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("author"),
        related_name="areas",
        on_delete=models.PROTECT,
    )

    district = models.ForeignKey(
        District,
        verbose_name=_("district"),
        related_name="areas",
        on_delete=models.PROTECT,
    )

    description = models.TextField(
        _("description"),
        help_text=_("Optional item"),
        blank=True,
    )

    is_deleted = models.BooleanField(_("is deleted?"), default=False, db_index=True)

    objects = models.Manager.from_queryset(AreaQS)()

    def get_absolute_url(self):
        return reverse("areas:detail", args=[self.id])

    def __str__(self):
        return _("Area") + f" #{self.id}"

    class Meta:
        verbose_name = _("area")
        verbose_name_plural = _("areas")


class SprayingPeriodQS(models.QuerySet):
    def recent(self, now):
        return self.filter(**recent_periods_filter(now))

    def active(self, now):
        return self.filter(**active_periods_filter(now))

    def inactive(self, now):
        return self.exclude(**active_periods_filter(now))


class SprayingPeriod(TimeStampedModel):
    class PestKind(models.IntegerChoices):
        FUNGI = 100, _("fungi")
        ANIMALS = 200, _("animals")
        PLANTS = 300, _("plants")

    pest_kind = models.SmallIntegerField(
        _("pest kind"),
        help_text=_("The type of pests against which the spray is applied"),
        choices=PestKind.choices,
    )
    executor = models.CharField(_("executor"), max_length=255)
    since = models.DateTimeField(_("since"))
    until = models.DateTimeField(_("until"))
    area = models.ForeignKey(
        "Area", verbose_name=_("area"), related_name="periods", on_delete=models.PROTECT
    )

    objects = models.Manager.from_queryset(SprayingPeriodQS)()

    def __str__(self):
        return _("Period") + f" #{self.id}"

    class Meta:
        verbose_name = _("spraying period")
        verbose_name_plural = _("spraying periods")

isopp/areas/forms.py
from bootstrap_datepicker_plus.widgets import DateTimePickerInput
from django.forms import ModelForm, Textarea, inlineformset_factory
from django.utils.translation import gettext_lazy as _
from leaflet.forms.widgets import LeafletWidget

from .models import Area, SprayingPeriod


class AreaForm(ModelForm):
    class Meta:
        model = Area
        fields = ("boundary", "district", "description")
        widgets = {
            "description": Textarea(attrs={"rows": "2"}),
            "boundary": LeafletWidget(),
        }


class SprayingPeriodForm(ModelForm):
    def clean(self):
        cleaned_data = super().clean()
        since = cleaned_data.get("since")
        until = cleaned_data.get("until")

        if since and until and since >= until:
            self.add_error("since", _("'Since' must be lower than 'Until'."))
            self.add_error("until", _("'Until' must be greater than 'Since'."))

    class Meta:
        model = SprayingPeriod
        fields = ("pest_kind", "executor", "since", "until", "area")
        widgets = {
            "since": DateTimePickerInput(
                attrs={"placeholder": "YYYY-MM-DD HH:MM", "class": "period-since"},
                options={"format": "YYYY-MM-DD HH:mm"},
            ),
            "until": DateTimePickerInput(
                attrs={"placeholder": "YYYY-MM-DD HH:MM", "class": "period-until"},
                options={"format": "YYYY-MM-DD HH:mm"},
            ),
        }


SprayingPeriodFormSet = inlineformset_factory(
    Area, SprayingPeriod, form=SprayingPeriodForm, extra=1, can_delete=False
)

isopp/api/areas/views.py
from contextlib import suppress

from areas.models import Area, SprayingPeriod
from django.contrib.gis.db.models.functions import Distance
from django.contrib.gis.geos import Point
from rest_framework import serializers
from rest_framework.decorators import api_view
from rest_framework.generics import get_object_or_404
from rest_framework.relations import RelatedField, StringRelatedField
from rest_framework.response import Response
from rest_framework_gis.serializers import GeoFeatureModelSerializer


class AuthorField(RelatedField):
    def to_representation(self, value):
        return value.organization


class SprayingPeriodSerializer(serializers.ModelSerializer):
    pest_kind = serializers.CharField(source="get_pest_kind_display")

    class Meta:
        model = SprayingPeriod
        fields = ("id", "pest_kind", "executor", "since", "until")


class AreaSerializer(GeoFeatureModelSerializer):
    author = AuthorField(read_only=True)
    district = StringRelatedField()
    periods = SprayingPeriodSerializer(many=True, read_only=True)

    class Meta:
        model = Area
        geo_field = "boundary"
        id_field = False
        fields = ("id", "author", "district", "description", "periods", "created")


@api_view()
def areas_list(request):
    qs = (
        Area.objects.valid()
        .select_related("author", "district")
        .prefetch_related("periods")
    )
    params = request.query_params

    if center := params.get("center"):
        with suppress(ValueError):
            lat, lng = center.split("|")
            loc = Point(float(lat), float(lng), srid=4326)
            qs = qs.annotate(distance=Distance("boundary", loc)).order_by("distance")

    if limit := params.get("limit"):
        with suppress(ValueError):
            qs = qs[: int(limit)]

    if author := params.get("author"):
        with suppress(ValueError):
            qs = qs.filter(author__id=int(author))

    if district := params.get("district"):
        with suppress(ValueError):
            qs = qs.filter(district__id=int(district))

    return Response(AreaSerializer(area).data for area in qs)


@api_view()
def area_detail(request, pk):
    qs = (
        Area.objects.valid()
        .select_related("author", "district")
        .prefetch_related("periods")
    )
    area = get_object_or_404(qs, pk=pk)

    return Response(AreaSerializer(area).data)

isopp/areas/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.serializers import serialize
from django.db import transaction
from django.http import Http404
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views import generic
from utils.serializers import AreasSerializer

from .forms import AreaForm, SprayingPeriodFormSet
from .models import Area, SprayingPeriod

logger = logging.getLogger(__name__)


class DetailView(generic.DetailView):

    template_name = "areas/detail.html"

    def get_object(self, queryset=None):
        try:
            pk = int(self.kwargs.get("pk"))
            return Area.objects.valid().select_related("author", "district").get(pk=pk)
        except (Area.DoesNotExist, ValueError):
            raise Http404

    def get_context_data(self, **kwargs):
        now = timezone.now()
        periods_qs = SprayingPeriod.objects.filter(area=self.object)
        periods_qs = (
            periods_qs.recent(now)
            if self.request.user.pk == self.object.author_id
            else periods_qs.active(now)
        )
        periods = periods_qs.all()

        self.object.filtered_periods = periods

        return {
            **super().get_context_data(**kwargs),
            "json": {
                "areas": AreasSerializer(now).serialize(
                    [self.object], geometry_field="boundary", fields=("status",)
                )
            },
            "periods_current": [p for p in periods if p.until >= now >= p.since],
            "periods_past": [p for p in periods if p.until < now],
            "periods_future": [p for p in periods if p.since > now],
        }


class UpdateView(SuccessMessageMixin, LoginRequiredMixin, generic.UpdateView):

    form_class = AreaForm
    template_name = "areas/update.html"
    success_message = _("The area was successfully updated.")
    login_url = reverse_lazy("accounts:sign-in")

    def get_object(self, queryset=None):
        try:
            pk = int(self.kwargs.get("pk"))
            return Area.objects.valid().get(pk=pk, author=self.request.user)
        except (Area.DoesNotExist, ValueError):
            raise Http404

    def get_context_data(self, **kwargs):
        periods_qs = SprayingPeriod.objects.recent(timezone.now())
        return {
            **super().get_context_data(**kwargs),
            "json": {"areas": serialize("geojson", [self.object])},
            "periods": (
                SprayingPeriodFormSet(
                    self.request.POST, instance=self.object, queryset=periods_qs
                )
                if self.request.POST
                else SprayingPeriodFormSet(instance=self.object, queryset=periods_qs)
            ),
        }

    def form_valid(self, form):
        periods = self.get_context_data().get("periods")

        with transaction.atomic():
            if periods.is_valid():
                response = super().form_valid(form)
                periods.instance = self.object
                periods.save()
                logger.info("Area % has been updated.", self.object.pk)
                return response
            else:
                return self.form_invalid(form)


class CreateView(SuccessMessageMixin, LoginRequiredMixin, generic.CreateView):

    form_class = AreaForm
    template_name = "areas/create.html"
    success_message = _("The area was successfully created.")
    login_url = reverse_lazy("accounts:sign-in")

    def get_context_data(self, **kwargs):
        return {
            **super().get_context_data(**kwargs),
            "periods": SprayingPeriodFormSet(self.request.POST)
            if self.request.POST
            else SprayingPeriodFormSet(),
        }

    def form_valid(self, form):
        periods = self.get_context_data().get("periods")

        with transaction.atomic():
            if periods.is_valid():
                form.instance.author = self.request.user
                form.instance.is_deleted = False
                response = super().form_valid(form)
                periods.instance = self.object
                periods.save()
                logger.info(
                    "Area %s has been created by %s", self.object.pk, self.request.user
                )
                return response
            else:
                return self.form_invalid(form)

isopp/templates/areas/base.html
{% extends 'base.html' %}
{% load i18n %}
{% load leaflet_tags %}

{% block title %}{% trans 'Areas' %} | {{ block.super }}{% endblock %}

{% block css %}
    {% leaflet_css plugins="forms" %}
{% endblock %}

{% block body_classes %}areas{% endblock %}

{% block content %}
    <div class="container-areas container-fluid">
        {% block areas %}
        {% endblock %}
    </div>
{% endblock %}

{% block js %}
    {% leaflet_js plugins="forms" %}
{% endblock %}

isopp/templates/areas/create.html
{% extends "areas/modify.html" %}
{% load i18n %}
{% load bootstrap4 %}

{% block title %}{% trans 'Create New Area' %} | {{ block.super }}{% endblock %}

{% block nav_create %}active{% endblock %}

{% block areas %}
    <h3>{% trans 'Create new area' %}</h3>

    {% for field in form.hidden_fields %}
        {% if field.errors %}
            {% include 'bootstrap4/form_errors.html' with errors=field.errors %}
        {% endif %}
    {% endfor %}

    <form class="areas-modify-form" method="post">
        {% csrf_token %}
        {% bootstrap_form form alert_error_type='all' %}

        <h6>{% trans 'Spraying periods' %}</h6>
        {% bootstrap_formset periods layout='horizontal' %}

        {% buttons %}
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
            <a href="{% url 'home' %}" class="btn btn-link">{% trans 'Cancel' %}</a>
        {% endbuttons %}
    </form>
{% endblock %}

isopp/templates/areas/detail.html
{% extends "areas/base.html" %}
{% load i18n %}
{% load bootstrap4 %}
{% load leaflet_tags %}

{% block title %}{% trans 'Area Detail' %} | {{ block.super }}{% endblock %}

{% block body_classes %}{{ block.super }} split-view{% endblock %}

{% block content %}
    {% leaflet_map "map" %}
    <div id="sidebar">
        <div class="sidebar-content">
            <h5>{% trans 'Author' %}</h5>
            <p>{{ area.author.organization }}</p>

            <h5>{% trans 'District' %}</h5>
            <p>{{ area.district.name }}</p>

            {% if area.description %}
                <h5>{% trans 'Description' %}</h5>
                <p>{{ area.description }}</p>
            {% endif %}

            {% if user.is_verified and user.pk == area.author.pk %}
                {% buttons %}
                    <a href="{% url 'areas:update' area.pk %}" class="btn btn-primary">{% trans 'Edit' %}</a>
                {% endbuttons %}
            {% endif %}
            {% if periods_current %}
                <div class="table-period-current">
                    <h5>{% trans 'Current spraying periods' %}</h5>
                    {% include "inc/periods_table.html" with periods=periods_current %}
                </div>
            {% endif %}
            {% if periods_future %}
                <div class="table-period-future">
                    <h5>{% trans 'Future spraying periods' %}</h5>
                    {% include "inc/periods_table.html" with periods=periods_future %}
                </div>
            {% endif %}
            {% if periods_past %}
                <div class="table-period-past">
                    <h5>{% trans 'Past spraying periods' %}</h5>
                    {% include "inc/periods_table.html" with periods=periods_past %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include "inc/footer.html" %}
{% endblock %}

{% block js %}
    {{ block.super }}
    {% include "inc/js/shape_styles.html" %}
    <script>
        window.addEventListener("map:init", function (e) {
            var map = e.detail.map;
            var areas = {{ json.areas|default:"[]"|safe }};

            L.geoJSON(areas, {
                onEachFeature: function (feature, layer) {
                    map.fitBounds(layer.getBounds());
                    layer.setStyle(shapeStyle[feature.properties.status]);
                }
            }).addTo(map);
        });
    </script>
{% endblock %}

isopp/templates/areas/modify.html
{% extends "areas/base.html" %}
{% load static %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'moment-with-locales.min.js' %}"></script>
    <script>moment.locale('{{ LANGUAGE_CODE }}')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script src="{% static 'bootstrap_datepicker_plus/js/datepicker-widget.js' %}"></script>
{% endblock %}

{% block css %}
    {{ block.super }}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css" type="text/css" media="all" rel="stylesheet">
    <link href="{% static 'bootstrap_datepicker_plus/css/datepicker-widget.css' %}" type="text/css" media="all" rel="stylesheet">
{% endblock %}

isopp/templates/areas/update.html
{% extends "areas/modify.html" %}
{% load i18n %}
{% load bootstrap4 %}

{% block title %}{% trans 'Update Area' %} | {{ block.super }}{% endblock %}

{% block areas %}
    <h3>{% trans 'Update area' %}</h3>

    {% for field in form.hidden_fields %}
        {% if field.errors %}
            {% include 'bootstrap4/form_errors.html' with errors=field.errors %}
        {% endif %}
    {% endfor %}

    <form class="areas-modify-form" method="post">
        {% csrf_token %}
        {% bootstrap_form form alert_error_type='all' %}

        <h6>{% trans 'Spraying periods' %}</h6>
        {% bootstrap_formset periods layout='horizontal' %}

        {% buttons %}
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
            <a href="{% url 'areas:detail' area.pk %}" class="btn btn-link">{% trans 'Cancel' %}</a>
        {% endbuttons %}
    </form>
{% endblock %}