isopp/accounts/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy

from .views import (
    SignUpCompleteView,
    SignUpConfirmView,
    SignUpDoneView,
    SignUpVerifyView,
    SignUpView,
)

urlpatterns = [
    path("sign-up/", SignUpView.as_view(), name="sign-up"),
    path("sign-up/done/", SignUpDoneView.as_view(), name="sign-up-done"),
    path(
        "sign-up/verify/<int:user_id>/", SignUpVerifyView.as_view(), name="sign-up-verify"
    ),
    path(
        "sign-up/<uidb64>/<token>/", SignUpConfirmView.as_view(), name="sign-up-confirm"
    ),
    path("sign-up/complete/", SignUpCompleteView.as_view(), name="sign-up-complete"),
    path(
        "sign-in/",
        LoginView.as_view(template_name="accounts/sign_in.html"),
        name="sign-in",
    ),
    path(
        "sign-out/",
        LogoutView.as_view(template_name="accounts/signed_out.html"),
        name="sign-out",
    ),
    path(
        "password-change/",
        PasswordChangeView.as_view(
            template_name="accounts/password_change.html",
            success_url=reverse_lazy("accounts:password-change-done"),
        ),
        name="password-change",
    ),
    path(
        "password-change/done/",
        PasswordChangeDoneView.as_view(
            template_name="accounts/password_change_done.html"
        ),
        name="password-change-done",
    ),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
            subject_template_name="accounts/password_reset_email_subject.txt",
            email_template_name="accounts/password_reset_email.txt",
            success_url=reverse_lazy("accounts:password-reset-done"),
        ),
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),
        name="password-reset-done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy("accounts:password-reset-complete"),
        ),
        name="password-reset-confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password-reset-complete",
    ),
]

isopp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

admin.sites.AdminSite.site_header = _("Administration")
admin.sites.AdminSite.site_title = _("Administration")
admin.sites.AdminSite.index_title = "ISOPP"


if settings.MAINTENANCE_MODE:
    urlpatterns = [
        re_path("/*", TemplateView.as_view(template_name="maintenance.html")),
    ]
else:
    urlpatterns = [
        path("", include("core.urls")),
        path("admin/", admin.site.urls),
        path("accounts/", include(("accounts.urls", "accounts"), namespace="accounts")),
        path("areas/", include(("areas.urls", "areas"), namespace="areas")),
        path("lang/", include("django.conf.urls.i18n")),
    ]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
        path("404/", TemplateView.as_view(template_name="404.html")),
        path("403/", TemplateView.as_view(template_name="403.html")),
        path("500/", TemplateView.as_view(template_name="500.html")),
    ] + urlpatterns

isopp/accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField


class UserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("Email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        extra_fields.setdefault("is_active", False)
        extra_fields.setdefault("is_email_verified", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)
        extra_fields.setdefault("is_email_verified", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class ActiveUserQuerySet(models.QuerySet):
    def active(self):
        return self.filter(is_active=True, is_email_verified=True)


class User(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(_("first name"), max_length=30, blank=True)
    last_name = models.CharField(_("last name"), max_length=150, blank=True)
    organization = models.CharField(_("organization"), max_length=255, blank=True)
    phone = PhoneNumberField(_("phone"), blank=True)
    email = models.EmailField(_("email address"), unique=True, blank=True)
    is_email_verified = models.BooleanField(_("is email verified?"), default=False)
    is_staff = models.BooleanField(
        _("is staff?"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("is active?"),
        default=False,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = UserManager.from_queryset(ActiveUserQuerySet)()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = "first_name", "last_name", "organization", "phone"

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    @property
    def is_verified(self):
        return self.groups.filter(name="verified").exists()

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}".strip()

    def get_short_name(self):
        return self.last_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

isopp/accounts/forms.py
import logging

from django import forms
from django.conf import settings
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from phonenumber_field.formfields import PhoneNumberField

from .models import User

logger = logging.getLogger(__name__)


class UserCreationAdminForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email",)


class UserChangeAdminForm(UserChangeForm):
    class Meta:
        model = User
        fields = "__all__"


class SignupForm(forms.ModelForm):
    first_name = forms.CharField(label=_("First name"), max_length=30, required=True)
    last_name = forms.CharField(label=_("Last name"), max_length=150, required=True)
    organization = forms.CharField(label=_("Organization"), required=True)
    phone = PhoneNumberField(label=_("Phone"), required=True)
    email = forms.EmailField(label=_("Email address"), required=True)

    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html(),
    )

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super().__init__(*args, **kwargs)

    def clean_password(self):
        password = self.cleaned_data.get("password")
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except forms.ValidationError as error:
                self.add_error("password", error)
        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        send_confirmation_email(self.request, user)
        return user

    class Meta:
        model = User
        fields = "first_name", "last_name", "organization", "phone", "email", "password"


def send_confirmation_email(request, user):
    current_site = get_current_site(request)
    subject = render_to_string("accounts/sign_up_email_subject.txt")
    message = render_to_string(
        "accounts/sign_up_email.txt",
        {
            "user": user,
            "protocol": "https" if request.is_secure() else "http",
            "domain": current_site.domain,
            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
            "token": default_token_generator.make_token(user),
        },
    )
    user.email_user(subject, message, settings.SIGNUP_EMAIL)
    logger.info("Signup confirmation email has been send to %s.", user.email)

isopp/accounts/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import Group
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import mail_managers
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_decode
from django.utils.translation import gettext_lazy as _
from django.views import generic

from .forms import SignupForm
from .models import User

logger = logging.getLogger(__name__)


class SignUpView(generic.CreateView):

    form_class = SignupForm
    success_url = reverse_lazy("accounts:sign-up-done")
    template_name = "accounts/sign_up.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def form_valid(self, form):
        logger.info(
            "User %s has successfully filled signup form.", form.cleaned_data["email"]
        )
        return super().form_valid(form)


class SignUpDoneView(generic.TemplateView):

    template_name = "accounts/sign_up_done.html"


INTERNAL_SIGNUP_SESSION_TOKEN = "_signup_token"
INTERNAL_SIGNUP_CONFIRMATION_TOKEN = "confirm"


class SignUpConfirmView(generic.View):

    template_name = "accounts/sign_up_confirm.html"
    http_method_names = ["get", "head", "options", "trace"]

    def get(self, request, uidb64, token):
        user = get_user(uidb64)

        if user:
            if token == INTERNAL_SIGNUP_CONFIRMATION_TOKEN:
                session_token = self.request.session.get(INTERNAL_SIGNUP_SESSION_TOKEN)
                if default_token_generator.check_token(user, session_token):
                    context = {
                        "link_valid": True,
                        "user": user,
                        "uidb64": uidb64,
                        "token": session_token,
                    }
                    logger.info("Signup confirmation form displayed for %s.", user.email)
                    return render(request, self.template_name, context)

            else:
                if default_token_generator.check_token(user, token):
                    request.session[INTERNAL_SIGNUP_SESSION_TOKEN] = token
                    redirect_url = request.path.replace(
                        token, INTERNAL_SIGNUP_CONFIRMATION_TOKEN
                    )
                    return HttpResponseRedirect(redirect_url)

        logger.warning(
            "Invalid signup confirmation displayed for user %s.", self.request.user.email
        )
        context = {"link_valid": False}
        return render(request, self.template_name, context)


def get_user(uidb64):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        return User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        return None


class SignUpCompleteView(generic.View):

    template_name = "accounts/sign_up_complete.html"

    def post(self, request):
        user = get_user(request.POST.get("uidb64"))
        token = request.POST.get("token")

        if user and default_token_generator.check_token(user, token):
            user.is_active = True
            user.is_email_verified = True
            user.save()
            logger.info("User % has been created.", user.email)
            login(request, user)
            send_verification_email(request, user)
            context = {"confirmation_valid": True, "user": user}
            return render(request, self.template_name, context)

        logger.warning("Invalid token or user during signup.")
        context = {"confirmation_valid": False}
        return render(request, self.template_name, context)

    def get(self, request):
        return redirect("home")


def send_verification_email(request, user):
    current_site = get_current_site(request)
    subject = render_to_string("accounts/sign_up_verify_email_subject.txt")
    message = render_to_string(
        "accounts/sign_up_verify_email.txt",
        {
            "user": user,
            "protocol": "https" if request.is_secure() else "http",
            "domain": current_site.domain,
        },
    )
    mail_managers(subject, message)
    logger.info("User verification link for %s has been sent to managers.", user.email)


class IsEditorMixin(UserPassesTestMixin):
    def test_func(self):
        if self.request.user.groups.filter(name="editor").exists():
            return True
        else:
            logger.warning(
                "Access to signup verification form denied for %s.",
                self.request.user.email,
            )
            return False


class SignUpVerifyView(IsEditorMixin, generic.DetailView):

    template_name = "accounts/sign_up_verify.html"
    queryset = User.objects.active()
    context_object_name = "user"
    pk_url_kwarg = "user_id"

    def post(self, request, **kwargs):
        verified = request.POST.get("verified")
        declined = request.POST.get("declined")
        self.object = user = self.get_object()

        group = Group.objects.get(name="verified")

        if verified:
            user.groups.add(group)
            messages.success(
                request, _("User {email} has been verified.").format(email=user.email)
            )
            send_email_verified(request, user)
            logger.info("Verification for %s has been granted.", user.email)

        if declined:
            user.groups.remove(group)
            messages.warning(
                request, _("User {email} has been declined.").format(email=user.email)
            )
            logger.warning("Verification for % has been declined.", user.email)

        context = self.get_context_data()
        return self.render_to_response(context)


def send_email_verified(request, user):
    current_site = get_current_site(request)
    subject = render_to_string("accounts/sign_up_verified_email_subject.txt")
    message = render_to_string(
        "accounts/sign_up_verified_email.txt",
        {
            "user": user,
            "protocol": "https" if request.is_secure() else "http",
            "domain": current_site.domain,
        },
    )
    user.email_user(subject, message, settings.SIGNUP_EMAIL)
    logger.info("Verification notice for %s has been sent.", user.email)

isopp/templates/accounts/base.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Accounts' %} | {{ block.super }}{% endblock %}

{% block body_classes %}accounts{% endblock %}

{% block navigation_items %}
{% endblock %}

{% block content %}
    <div class="container-accounts container-fluid">
        {% block accounts %}
        {% endblock %}
    </div>
{% endblock %}

isopp/templates/accounts/password_change.html
{% extends 'accounts/base.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block title %}{% trans 'Change Password' %} | {{ block.super }}{% endblock %}

{% block accounts %}
    <h3>{% trans 'Change password' %}</h3>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">{% trans 'Change password' %}</button>
        {% endbuttons %}
    </form>
{% endblock %}

isopp/templates/accounts/password_change_done.html
{% extends 'accounts/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Password Changed' %}{{ block.super }}{% endblock %}

{% block accounts %}
    <h3>{% trans 'Your password has been changed.' %}</h3>
    <p><a href="{% url 'home' %}">{% trans 'Go to the map' %}</a>.</p>
{% endblock %}

isopp/templates/accounts/password_reset.html
{% extends 'accounts/base.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block title %}{% trans 'Reset Password' %} | {{ block.super }}{% endblock %}

{% block accounts %}
    <h3>{% trans 'Reset password' %}</h3>
    <p>{% trans "Enter your email address that you used to sign up. We'll send you an email with a link to reset your password." %}</p>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">{% trans 'Reset password' %}</button>
        {% endbuttons %}
    </form>
{% endblock %}

isopp/templates/accounts/password_reset_complete.html
{% extends 'accounts/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Password Reset Complete' %}{{ block.super }}{% endblock %}

{% block accounts %}
    <h3>{% trans 'You have successfully changed your password.' %}</h3>
    <p><a href="{% url 'accounts:sign-in' %}">{% trans 'Sign in' context 'infinitive' %}</a></p>
{% endblock %}

isopp/templates/accounts/password_reset_confirm.html
{% extends 'accounts/base.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block title %}{% trans 'Set New Password' %} | {{ block.super }}{% endblock %}

{% block accounts %}
    {% if validlink %}
        <h3>{% trans 'Set new password' %}</h3>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">{% trans 'Set new password' %}</button>
            {% endbuttons %}
        </form>
    {% else %}
        <h3>{% trans 'Password reset failed' %}</h3>
        {% url "accounts:password-reset" as reset_url %}
        <p>{% blocktrans %}The password reset link was invalid, possibly because it has already been used. Please request <a href="{{ reset_url }}">a new password reset</a>.{% endblocktrans %}</p>
    {% endif %}
{% endblock %}

isopp/templates/accounts/password_reset_done.html
{% extends 'accounts/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Password Reset' %} | {{ block.super }}{% endblock %}

{% block accounts %}
    <h3>{% trans 'Your password was reset.' %}</h3>
    <p>{% trans "We've emailed you instructions for setting new password. If they haven't arrived in a few minutes, check your spam folder." %}</p>
{% endblock %}

isopp/templates/accounts/sign_in.html
{% extends 'accounts/base.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block title %}{% trans 'Sign In' %} | {{ block.super }}{% endblock %}

{% block accounts %}
    <h3>{% trans 'Sign in' %}</h3>

    <p><strong>{% trans 'Sign-in is required only for map editors and is not necessary for using the map.' %}</strong></p>

    {% if form.errors %}
        <p>{% trans "Your email and password didn't match. Please try again." %}</p>
    {% endif %}

    {% if next %}
        {% if user.is_authenticated %}
            <p>{% trans "Your account doesn't have access to this page. To proceed, please sign in with an account that has access." %}</p>
        {% else %}
            <p>{% trans "Please sign in to see this page." %}</p>
        {% endif %}
    {% endif %}

    <form method="post" action="{% url 'accounts:sign-in' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="hidden" name="next" value="{{ next }}">
        {% buttons %}
            <button type="submit" class="btn btn-primary">{% trans 'Sign in' context 'infinitive' %}</button>
        {% endbuttons %}
    </form>

    <p><a href="{% url 'accounts:sign-up' %}">{% trans "Don't have an account?" %}</a></p>
    <p><a href="{% url 'accounts:password-reset' %}">{% trans "Lost your password?" %}</a></p>

{% endblock %}

isopp/templates/accounts/sign_up.html
{% extends 'accounts/base.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block title %}{% trans 'Sign Up' %} | {{ block.super }}{% endblock %}

{% block accounts %}
    <h3>{% trans 'Sign up' %}</h3>

    <p><strong>{% trans 'Sign-up is required only for map editors and is not necessary for using the map.' %}</strong></p>

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">{% trans 'Sign up' %}</button>
        {% endbuttons %}
    </form>
{% endblock %}

isopp/templates/accounts/sign_up_complete.html
{% extends 'accounts/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Account Confirmation' %} | {{ block.super }}{% endblock %}

{% block accounts %}
    {% if confirmation_valid %}
        <h3>{% trans 'Account confirmation successful' %}</h3>
        <p>{% blocktrans with username=user.get_full_name %}You are signed in as {{ username }}{% endblocktrans %}</p>
        <p><strong>{% trans 'Please stand by for manual verification to be able to add areas to the map.' %}</strong></p>
        <p>{% trans 'You will be notified by email when your verification is ready.' %}</p>
        <p><a href="{% url 'home' %}">{% trans 'Go to the map' %}</a>.</p>
    {% else %}
        <h3>{% trans 'Account confirmation failed.' %}</h3>
        <p>{% blocktrans %}The confirmation link was invalid, possibly because it has already been used. Please contact us at <a href="mailto:info@zonybezpesticidov.sk?subject=Confirmation link invalid">info@zonybezpesticidov.sk</a>.{% endblocktrans %}</p>
    {% endif %}
{% endblock %}

isopp/templates/accounts/sign_up_confirm.html
{% extends 'accounts/base.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block title %}{% trans 'Account Confirmation' %} | {{ block.super }}{% endblock %}

{% block accounts %}
    {% if link_valid %}
        <h3>{% trans 'Account confirmation for' %} {{ user.email }}</h3>
        {% with username=user.get_full_name email=user.email %}
            <p>
                {% blocktrans %}Please confirm that email {{ email }} belongs to user {{ username }}.{% endblocktrans %}
            </p>
        {% endwith %}
        <form method="post" action="{% url 'accounts:sign-up-complete' %}">
            {% csrf_token %}
            <input type="hidden" name="uidb64" value="{{ uidb64 }}">
            <input type="hidden" name="token" value="{{ token }}">
            <button type="submit" class="btn btn-primary">{% trans "Confirm" %}</button>
        </form>
    {% else %}
        <h3>{% trans 'Account confirmation failed.' %}</h3>
        <p>{% blocktrans %}The confirmation link was invalid, possibly because it has already been used. Please contact us at <a href="mailto:info@zonybezpesticidov.sk?subject=Confirmation link invalid">info@zonybezpesticidov.sk</a>.{% endblocktrans %}</p>
    {% endif %}
{% endblock %}

isopp/templates/accounts/sign_up_done.html
{% extends 'accounts/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Signed Up' %} | {{ block.super }}{% endblock %}

{% block accounts %}
    <h3>{% trans 'Thank you for signing up.' %}</h3>
    <p>{% trans 'Please check your email for a confirmation link.' %}</p>
{% endblock %}

isopp/templates/accounts/sign_up_verify.html
{% extends 'accounts/base.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block title %}{% trans 'Account Verification' %} | {{ block.super }}{% endblock %}

{% block body_classes %}accounts-verification{% endblock %}

{% block accounts %}
    <h3>{% trans 'Account verification for' %} {{ user.email }}</h3>

    <table class="table table-sm table-borderless">
        <tr>
            <th>{% trans 'first name' %}</th>
            <td>{{ user.first_name }}</td>
        </tr>
        <tr>
            <th>{% trans 'last name' %}</th>
            <td>{{ user.last_name }}</td>
        </tr>
        <tr>
            <th>{% trans 'organization' %}</th>
            <td>{{ user.organization }}</td>
        </tr>
        <tr>
            <th>{% trans 'phone' %}</th>
            <td>{{ user.phone }}</td>
        </tr>
        <tr>
            <th>{% trans 'email address' %}</th>
            <td>{{ user.email }}</td>
        </tr>
    </table>
    {% with user_verified=user.is_verified %}
        {% if user_verified %}
            <p>{% trans 'User is verified.' %}</p>
        {% else %}
            <p>{% trans 'User is not verified.' %}</p>
        {% endif %}

        {% buttons %}
            <form method="post" action="{% url 'accounts:sign-up-verify' user.pk %}">
                {% csrf_token %}
                <input type="hidden" name="declined" value="true">
                <button type="submit" class="btn btn-outline-warning">{% trans "Decline" %}</button>
            </form>

            {% if not user_verified %}
                <form method="post" action="{% url 'accounts:sign-up-verify' user.pk %}">
                    {% csrf_token %}
                    <input type="hidden" name="verified" value="true">
                    <button type="submit" class="btn btn-primary">{% trans "Verify" %}</button>
                </form>
            {% endif %}
        {% endbuttons %}
    {% endwith %}
{% endblock %}

isopp/templates/accounts/signed_out.html
{% extends 'accounts/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Signed Out' %} | {{ block.super }}{% endblock %}

{% block accounts %}
    <h3>{% trans 'You have been signed out.' %}</h3>
    <p><a href="{% url 'accounts:sign-in' %}">{% trans 'Sign in again' %}</a></p>
{% endblock %}