isopp/accounts/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy

from .views import (
    SignUpCompleteView,
    SignUpConfirmView,
    SignUpDoneView,
    SignUpVerifyView,
    SignUpView,
)

urlpatterns = [
    path("sign-up/", SignUpView.as_view(), name="sign-up"),
    path("sign-up/done/", SignUpDoneView.as_view(), name="sign-up-done"),
    path(
        "sign-up/verify/<int:user_id>/", SignUpVerifyView.as_view(), name="sign-up-verify"
    ),
    path(
        "sign-up/<uidb64>/<token>/", SignUpConfirmView.as_view(), name="sign-up-confirm"
    ),
    path("sign-up/complete/", SignUpCompleteView.as_view(), name="sign-up-complete"),
    path(
        "sign-in/",
        LoginView.as_view(template_name="accounts/sign_in.html"),
        name="sign-in",
    ),
    path(
        "sign-out/",
        LogoutView.as_view(template_name="accounts/signed_out.html"),
        name="sign-out",
    ),
    path(
        "password-change/",
        PasswordChangeView.as_view(
            template_name="accounts/password_change.html",
            success_url=reverse_lazy("accounts:password-change-done"),
        ),
        name="password-change",
    ),
    path(
        "password-change/done/",
        PasswordChangeDoneView.as_view(
            template_name="accounts/password_change_done.html"
        ),
        name="password-change-done",
    ),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
            subject_template_name="accounts/password_reset_email_subject.txt",
            email_template_name="accounts/password_reset_email.txt",
            success_url=reverse_lazy("accounts:password-reset-done"),
        ),
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),
        name="password-reset-done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy("accounts:password-reset-complete"),
        ),
        name="password-reset-confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password-reset-complete",
    ),
]

isopp/areas/urls.py
from django.urls import path

from .views import CreateView, DetailView, UpdateView

urlpatterns = [
    path("detail/<pk>/", DetailView.as_view(), name="detail"),
    path("update/<pk>/", UpdateView.as_view(), name="update"),
    path("create/", CreateView.as_view(), name="create"),
]

isopp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

admin.sites.AdminSite.site_header = _("Administration")
admin.sites.AdminSite.site_title = _("Administration")
admin.sites.AdminSite.index_title = "ISOPP"


if settings.MAINTENANCE_MODE:
    urlpatterns = [
        re_path("/*", TemplateView.as_view(template_name="maintenance.html")),
    ]
else:
    urlpatterns = [
        path("", include("core.urls")),
        path("admin/", admin.site.urls),
        path("accounts/", include(("accounts.urls", "accounts"), namespace="accounts")),
        path("areas/", include(("areas.urls", "areas"), namespace="areas")),
        path("lang/", include("django.conf.urls.i18n")),
    ]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
        path("404/", TemplateView.as_view(template_name="404.html")),
        path("403/", TemplateView.as_view(template_name="403.html")),
        path("500/", TemplateView.as_view(template_name="500.html")),
    ] + urlpatterns

isopp/templates/_base.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
    <meta name="author" content="Ondřej Nejedlý">
    <meta name="description" content="{% trans 'Information system on pesticide use' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicons/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'favicons/safari-pinned-tab.svg' %}" color="#b63a48">
    <link rel="shortcut icon" href="{% static 'favicons/favicon.ico' %}">
    <meta name="apple-mobile-web-app-title" content="ISOPP">
    <meta name="application-name" content="ISOPP">
    <meta name="msapplication-TileColor" content="#ffc40d">
    <meta name="msapplication-config" content="{% static 'favicons/browserconfig.xml' %}">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/isopp.css' %}">
    <link rel="stylesheet" href="{% static 'awesome/css/font-awesome.min.css' %}">
    {% block css %}
    {% endblock %}
    {% block analytics %}
    {% endblock %}
    <title>{% block title %}ISOPP{% endblock %}</title>
</head>
<body class="{% block body_classes %}{% endblock %}">
    {% if MAINTENANCE_MODE %}
        {% block maintenance %}
        {% endblock %}
    {% else %}
        {% block navigation %}
        {% endblock %}

        {% block messages %}
        {% endblock %}

        {% block content %}
        {% endblock %}

        {% block footer %}
        {% endblock %}

    <script src="https://code.jquery.com/jquery-3.6.1.slim.min.js"
            integrity="sha256-w8CvhFs7iHNVUtnSP0YKEg00p9Ih13rlL9zGqvLdePA="
            crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
            integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
            crossorigin="anonymous"></script>

        {% block js %}
        {% endblock %}
    {% endif %}
</body>
</html>

isopp/templates/about.html
{% extends "base.html" %}
{% load i18n %}
{% load leaflet_tags %}

{% block css %}
    {% leaflet_css %}
{% endblock %}

{% block title %}{% trans 'About' %} | {{ block.super }}{% endblock %}

{% block body_classes %}about split-view{% endblock %}

{% block nav_about %}active{% endblock %}

{% block content %}
    {% leaflet_map "map" %}
    {% include "inc/filter.html" %}
    <div id="sidebar">
        <div class="sidebar-content">
            <h5>{% trans 'What is ISOPP?' %}</h5>
            <p> {% blocktrans trimmed %}
                Information system on pesticide use is an online-based system for mediating public information regarding
                the application of pesticides in urban and rural areas of cities and villages.
                {% endblocktrans %}</p>
            <p> {% blocktrans trimmed %}
                The operating principle of the system is that actors (persons and institutions that apply pesticides,
                such as farmers, foresters, municipal authorities, railway operators, etc.) provide data concerning the
                place and time of spraying, while the system displays the area, date and information on "actors".
                {% endblocktrans %}</p>
            <p> {% blocktrans trimmed %}
                Thanks to a clear and simple user interface, information is displayed to citizens on a comprehensible
                map, free of charge and without the need for registration.
                {% endblocktrans %}</p>
            <h6>{% trans 'Project goals' %}</h6>
            <ul>
                <li>{% blocktrans trimmed %}
                    to provide public with the information on planned spraying before it is carried out, so that the
                    public
                    can avoid the sites in question to protect their health from the negative effects of pesticides and
                    also to protect domestic or livestock animals (including hives)
                    {% endblocktrans %}</li>
                <li>{% blocktrans trimmed %}
                    to provide an easy and accessible way to obtain information on pesticide use
                    {% endblocktrans %}</li>
                <li>{% blocktrans trimmed %}
                    to increase awareness of pesticide application in the Slovak Republic
                    {% endblocktrans %}</li>
            </ul>
            <p><strong>
                {% blocktrans trimmed %}
                For more information about pesticides and other projects of the civic association Zones Without
                Pesticides, please visit <a href="https://www.zonybezpesticidov.sk/">www.zonybezpesticidov.sk</a>.
                {% endblocktrans %}
            </strong></p>
            <h6>{% trans 'Contact' %}</h6>
            <p>Škovránčia 2956/3<br>81106 Bratislava</p>
            <p><a href="mailto:info@zonybezpesticidov.sk">info@zonybezpesticidov.sk</a></p>
            <p><a href="tel:00421915245763">+421 915 245 763</a></p>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include "inc/footer.html" %}
{% endblock %}

{% block js %}
    {% leaflet_js %}
    {% include "inc/js/map.html" %}
    {% include "inc/js/timeout.html" %}
{% endblock %}

isopp/templates/base.html
{% extends "_base.html" %}
{% load i18n %}
{% load static %}
{% load bootstrap4 %}

{% block analytics %}
    {% if not DEBUG %}
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-6140888-21"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-6140888-21');
    </script>
    {% endif %}
{% endblock %}

{% block messages %}
    {% if messages %}
        <div id="messages">
            {% bootstrap_messages %}
        </div>
    {% endif %}
{% endblock %}

{% block navigation %}
    {% with user_is_verified=user.is_verified user_is_authenticated=user.is_authenticated %}
        <nav class="navbar navbar-expand-lg">
            <a class="navbar-brand color-brand" title="Informačný systém o používaní pesticídov" href="{% url 'home' %}?ResetMap=True">
                <img class="navbar-logo"
                     src="{% static 'logo.svg' %}"
                     alt="logo"
                ><span class="navbar-desc">
                    {% trans 'Information system on&nbsp;pesticide use' %}
                </span>
            </a>
            {% block navigation_items %}
                <button class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navigation"
                        aria-controls="navigation"
                        aria-expanded="false"
                        aria-label="{% trans 'Toggle navigation' %}">
                    <i class="fa fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navigation">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link {% block nav_about %}{% endblock %}" href="{% url 'about' %}">
                                {% trans 'About' %}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% block nav_legend %}{% endblock %}" href="{% url 'legend' %}">
                                {% trans 'Legend' %}
                            </a>
                        </li>
                        {% if user_is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link {% block nav_my_account %}{% endblock %}" href="{% url 'my-account' %}">
                                    {% trans 'My account' %}
                                    {% if user_is_verified %}
                                        <i class="fa fa-check-circle text-success" title="{% trans 'Verified user' %}"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle text-danger" title="{% trans 'Unverified user' %}"></i>
                                    {% endif %}
                                </a>
                            </li>
                            {% if user_is_verified %}
                                <li class="nav-item">
                                    <a class="nav-link {% block nav_create %}{% endblock %}" href="{% url 'areas:create' %}">
                                        {% trans 'Create area' %}
                                    </a>
                                </li>
                            {% endif %}
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link {% block nav_sign_in %}{% endblock %}" href="{% url 'accounts:sign-in' %}">
                                    {% trans 'Sign in' context 'infinitive' %}
                                </a>
                            </li>
                        {% endif %}
                        <li class="nav-item languages">
                            {% include 'inc/languages.html' %}
                        </li>
                    </ul>
                </div>
            {% endblock navigation_items %}
        </nav>
    {% endwith %}
{% endblock navigation %}

isopp/templates/home.html
{% extends 'base.html' %}
{% load leaflet_tags %}

{% block css %}
    {% leaflet_css %}
{% endblock %}

{% block content %}
    {% leaflet_map "map" %}
    {% include "inc/filter.html" %}
{% endblock %}

{% block footer %}
    {% include "inc/footer.html" %}
{% endblock %}

{% block js %}
    {% leaflet_js %}
    {% include "inc/js/map.html" %}
    {% include "inc/js/timeout.html" %}
    <script>
        window.addEventListener("map:init", function (e) {
            new L.Hash(e.detail.map);
        });
    </script>
{% endblock %}

isopp/templates/http_errors.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Error' %} | {{ block.super }}{% endblock %}

{% block content %}
    <div class="container-errors container-fluid">
        <h3>{% block error_title %}{% endblock %}</h3>
        {% block error_description %}{% endblock %}
    </div>
{% endblock %}

isopp/templates/legend.html
{% extends "base.html" %}
{% load i18n %}
{% load leaflet_tags %}

{% block css %}
    {% leaflet_css %}
{% endblock %}

{% block title %}{% trans 'Legend' %} | {{ block.super }}{% endblock %}

{% block body_classes %}legend split-view{% endblock %}

{% block nav_legend %}active{% endblock %}

{% block content %}
    {% leaflet_map "map" %}
    {% include "inc/filter.html" %}
    <div id="sidebar">
        <div class="sidebar-content">
            <h5>{% trans 'Legend' %}</h5>
            <div class="legend-bar legend-bar-past"></div>
            <p>{% trans 'If the area is marked in green, it means that the spraying took place a week ago or earlier.' %}</p>
            <div class="legend-bar legend-bar-future"></div>
            <p>{% trans 'If the area is marked in orange, it means that the spraying will take place one day or earlier.' %}</p>
            <div class="legend-bar legend-bar-current"></div>
            <p>{% trans 'If the area is marked in red, it means that the spraying is taking place right now.' %}</p>
            <svg class="legend-symbol"><use xlink:href='#marker'></use></svg>
            <p>{% trans 'This symbol indicates areas that have been, are, or going to be affected by spraying.' %}</p>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include "inc/footer.html" %}
{% endblock %}

{% block js %}
    {% leaflet_js %}
    {% include "inc/js/map.html" %}
    {% include "inc/js/timeout.html" %}
{% endblock %}

isopp/templates/maintenance.html
{% extends "_base.html" %}
{% load i18n %}

{% block maintenance %}

    <div class="container">
        <h1 class="d-flex justify-content-center mt-5">{% trans "Coming soon" %}</h1>
    </div>

{% endblock %}

isopp/templates/my_account.html
{% extends "base.html" %}
{% load i18n %}
{% load leaflet_tags %}

{% block css %}
    {% leaflet_css %}
{% endblock %}

{% block title %}{% trans 'My Account' %} | {{ block.super }}{% endblock %}

{% block body_classes %}my-account split-view{% endblock %}

{% block nav_my_account %}active{% endblock %}

{% block content %}
    {% leaflet_map "map" %}
    <div id="sidebar">
        <div class="sidebar-content">
            <h5>{% trans 'You are signed in as' %}</h5>
            <p>{{ user.get_full_name }} ({{ user.email }})</p>

            <h5>{% trans 'Organization' %}</h5>
            <p>{{ user.organization }}</p>

            <h5>{% trans 'Links' %}</h5>
            <p><a href="{% url 'accounts:sign-out' %}">{% trans 'Sign out' %}</a></p>
            <p><a href="{% url 'accounts:password-change' %}">{% trans 'Change password' %}</a></p>
            {% if user.is_staff %}
                <p><a href="{% url 'admin:index' %}">{% trans 'Administration' %}</a></p>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include "inc/footer.html" %}
{% endblock %}

{% block js %}
    {% leaflet_js %}
    {% include "inc/js/map.html" %}
{% endblock %}